### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by LUMLUMvr** [BOLL7708/OpenVR2Key#38] opened 2023-03-02 02:53 UTC
when I run the app it won't work, and current app id just says default and I don't know how to fix it.
![Screenshot (97)](https://user-images.githubusercontent.com/126740480/222318972-4629382e-b43c-4fe7-b281-4140e64d1f37.png)

**Comment by BOLL7708** [comment] 2023-03-02 08:16
Default means no scene application is detected, so the default profile is used, what game are you running at the same time?

Also as a side note, do you come from a specific online community where this application was mentioned? This is the third issue posted in the same day which is highly irregular 😅

**Comment by LUMLUMvr** [comment] 2023-03-02 17:46
I found this app from a youtuber, so I guess that counts as yes btw thx for the info.

**Comment by BOLL7708** [comment] 2023-03-02 19:42
Does it work for you as intended now? It seems like it so I'll close this issue, thanks 😁

**Closed by BOLL7708** 2023-03-02 19:42 UTC

**Comment by LUMLUMvr** [comment] 2023-03-02 19:46
It works now thanks.
